on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mycrdemo1.azurecr.io
        username: ${{ secrets.acr_mycrdemo1_username }}
        password: ${{ secrets.acr_mycrdemo1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mycrdemo1.azurecr.io/myaks1:${{ github.sha }}
        docker push mycrdemo1.azurecr.io/myaks1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks19aea | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks19aea`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks19aea
        container-registry-url: mycrdemo1.azurecr.io
        container-registry-username: ${{ secrets.acr_mycrdemo1_username }}
        container-registry-password: ${{ secrets.acr_mycrdemo1_password }}
        secret-name: myaks1dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks19aea
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mycrdemo1.azurecr.io/myaks1:${{ github.sha }}
        imagepullsecrets: |
          myaks1dockerauth